### ISSUE TITLE
Jio Channel are not playing 

### ISSUE THREAD

**Issue by masternkv** [tobalan/tobalan.github.io#14]
From afternoon JIO tv movie channel are not playing

**Comment by masternkv** [comment]
@krreet @lavish440  can you please check

**Comment by CelestialLemon** [comment]
Not working for me since last week as well. When I click on a channel the spinner keeps spinning and after 5 minutes it says HTTP connection error max tries exceed .... something ... . Is this an error on my side? tried many different plugins / kodi versions nothing worked. @lavish440 @krreet
