### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Dark2711** [tobalan/tobalan.github.io#24]

**Comment by zenom141** [comment]
As there is no update for kodi addon. I have found temporary solution. U can use this app on android tv and also for mobile. https://github.com/jtvpremium/jio-jtv-premium

i have checked all sony channels are working.

**Comment by zenom141** [comment]
i found this live link for sab hd playing in vlc. https://dai.google.com/linear/hls/event/CrTivkDESWqwvUj3zFEYEA/master.m3u8

**Comment by rjprimeverse** [comment]
@zenom141 can you please give live link for sony sab as well
