### ISSUE TITLE
Adding movie section from jio tv

### ISSUE THREAD

**Issue by velmurugan274** [tobalan/tobalan.github.io#25]
Is it possible to add movies section from jio tv mobile app just like how channels section is present?

**Comment by technofreak24** [comment]
> @velmurugan274  Is it possible to add movies section from jio tv mobile app just like how channels section is present?

Yes. It is possible in KODI to add **Movies** section like **JioTV App/Web** ( https://www.jiotv.com/movies ) with sub-sections like **Popular Tamil Movie Channels** ( https://www.jiotv.com/list/popular-tamil-movie-channels/tv_p_ijK9xCFq_ )
Addition of other sections like **Sports, Specials, Kids, News, Shows** are also possible by coding.
