### ISSUE TITLE
Sony all channels now working

### ISSUE THREAD

**Issue by nexusbeans** [tobalan/tobalan.github.io#26]

**Comment by pradyparanjpe** [comment]
## Description
(Since nothing was provided by OP)
- Many Sony channels either show black screen. (e.g. Set Max)
- Some Sony channels display a banner that reads "We'll be back soon" (e.g. Sony Marathi)
- All other channels are work file.

## Accessible via JioTV mobile App
- I can access all these Sony channels on JioTV Mobile app.

**Comment by technofreak24** [comment]
@nexusbeans Yes. All Sony channels are working fine after updating to the latest API and code and Thanks for letting us know 👍🏻

**Comment by technofreak24** [comment]
@nexusbeans Yes. All Sony channels are working fine after updating to the latest API and code. Thanks for letting us know 👍🏻

**Comment by rjprimeverse** [comment]
@technofreak24 please tell the procedure to update api and code

**Comment by technofreak24** [comment]
As told by Tobalan in Discord server:
Change the version code to 330
Use the playback url `https://jiotvapi.media.jio.com/playback/apis/v1/geturl?langId=6`
Login by OTP only as it is the only way to get authToken and then refresh token as needed
All the channels will work perfectly.

**Comment by rjprimeverse** [comment]
@technofreak24 dude I don't know about python how to get auth token and refresh

**Comment by rjprimeverse** [comment]
@technofreak24 and also please tell how to change version to 330 as I am not a developer

**Comment by amit139313** [comment]
Hi @technofreak24 @rjprimeverse -- Kindly share the discord server link so that i can also fix the sony channel issue...
I am a python developer so i will be able to follow any instructions...

**Comment by technofreak24** [comment]
> @amit139313 amit Kindly share the discord server link 

Invite Link is given below (will expire in 6 days)
[KODI Addons Discord Server](https://discord.com/invite/khUvDAJH)

**Comment by rjprimeverse** [comment]
@technofreak24 can you please give your telegram I'd I want to connect you please

**Comment by technofreak24** [comment]
JioTV is testing **Channel 1017 Shrimad Ramayan**
![screenshot00009_054647](https://github.com/tobalan/tobalan.github.io/assets/121749085/fa1e07c7-3b48-4c37-8373-d173eb37e897)

![screenshot00008_054702](https://github.com/tobalan/tobalan.github.io/assets/121749085/67653e78-3c07-4a65-843a-fb7a1ec7febb)

**Comment by technofreak24** [comment]
@rjprimeverse @amit139313 Here is the discord link [**KODI Addons**](https://discord.com/invite/bYSv8v6E)

**Comment by zenom141** [comment]
> @nexusbeans Yes. All Sony channels are working fine after updating to the latest API and code. Thanks for letting us know 👍🏻

Hello, Can u tell me where to change link in plugin file? As in 2.3.9 Sony channels not working. Thanks

**Comment by jimit-creator** [comment]
Anyone fixed this issue?

**Comment by advpraggyl** [comment]
Please share the discord invite link. As previous link is expired. I want to solve the sony channels issue

**Comment by niracle** [comment]
https://github.com/tobalan/tobalan.github.io/issues/21#issuecomment-1929394440 seems like to fix the issue

**Comment by niracle** [comment]
@technofreak24 @nexusbeans could you please share discord link since the above link is expired, could you share steps on how to update ??
Change the version code to 330
Use the playback url https://jiotvapi.media.jio.com/playback/apis/v1/geturl?langId=6
Login by OTP only as it is the only way to get authToken and then refresh token as needed

**Comment by advpraggyl** [comment]
@technofreak24 @nexusbeans Can you please share the working discord link to Kodi Addons as we are unable to join discord through earlier links. Waiting since long for the song channel issue

**Comment by virubhai22** [comment]
https://github.com/tobalan/tobalan.github.io/issues/42#issuecomment-2151411198
