### ISSUE TITLE
Jio TV Error

### ISSUE THREAD

**Issue by Hardik28112** [tobalan/tobalan.github.io#3]
Jio TV not working
It is showing

"JIO TV Error 
Check the log for more information"

Can you fix this ?
Thanks a lot

Also please update discord link on your website
Previous one not working

Added screenshot
![Screenshot_20230709-011857_Kodi](https://github.com/tobalan/tobalan.github.io/assets/139011464/3725a315-4726-438b-8948-a095d6f589ca)

**Comment by kchariharan** [comment]
The Code quick repo is broken, update the dependency once the below PR is merged
https://github.com/willforde/script.module.codequick/pull/53

**Comment by Mujtiba** [comment]
Same error here

**Comment by technofreak24** [comment]
> Jio TV not working It is showing
Can you fix this ? Thanks a lot

[Solution to the error](https://github.com/krreet/plugin.video.jiotv/issues/83#issuecomment-1624504638) and the [active discord link](https://discord.gg/MgtR9EQxz5) was given 4 days back on https://github.com/krreet/plugin.video.jiotv/issues/83#issuecomment-1624504638

> Also please update discord link on your website Previous one not working
[Updated active discord server link](https://discord.gg/MgtR9EQxz5)

**Comment by Hardik28112** [comment]
Thank you so much 😊
