### ISSUE TITLE
Please add support to Kodi 18 version

### ISSUE THREAD

**Issue by charan0017** [tobalan/tobalan.github.io#30]
I am having Old TV in which at maximum Kodi version 18 is possible.

**Comment by technofreak24** [comment]
Downgrade the Addon code to Python 2 and Addon will work great in KODI Leia version 18 on old TV or old Set-top box/FireTV Stick.

**Comment by technofreak24** [comment]
This is KODI Leia 18 version from BotAllen. Just update the APIs and it should work great.
https://github.com/botallen/plugin.video.jiotv/tree/c9f665114195454336a11de6f4f2ccb6196052c5

**Comment by charan0017** [comment]
@technofreak24 By updating the APIs you mean to fork the repo of this version & compare with the current version and update the Login API system? Thanks for replying.

**Comment by technofreak24** [comment]
> @charan0017  update the Login API system? Thanks for replying.

No. Only update the API URL for Channel List and Channel URL (copy from TobAlan Addon constants.py file)
Rest everything will remain same.

**Comment by charan0017** [comment]
> https://github.com/botallen/plugin.video.jiotv/tree/c9f665114195454336a11de6f4f2ccb6196052c5

But @technofreak24 the login system of this version is also different right, its asking userid/mobile number with password, instead of OTP. How can we overcome this?

**Comment by technofreak24** [comment]
Use Email address or Jio Mobile Number with Jio Selfcare password as it has Auto-login function.
OTP login session expires after every 20 days unless there is refreshToken like in newer version of JioTV Python 3 addon which your TV may not support
