### ISSUE TITLE
Jio Tv is not installing

### ISSUE THREAD

**Issue by teja3raja** [tobalan/tobalan.github.io#31]
Today morning i tried to open the Jio tv. It was not working. I removed it and reinstalled it again. Then the installation itself is failing. If some times it got installed, the channels are not working. It is a critical issue. Please resolve it ASAP.

**Comment by teja3raja** [comment]
If the installation is successful, then the channels are not playing after login

**Comment by technofreak24** [comment]
@teja3raja JioTV addon is working good and all channels are playing. I checked just now *(Sat, 16 March 2024 at 1:53 PM)* and JioTV addon is fine.

**Comment by virubhai22** [comment]
> @teja3raja JioTV addon is working good and all channels are playing. I checked just now _(Sat, 16 March 2024 at 1:53 PM)_ and JioTV addon is fine.

But Sony channels still not working

**Comment by technofreak24** [comment]
> @virubhai22 

Sony channels are also working on JioTV with new updates.
**Sony For You**
https://www.jiotv.com/list/sony-for-you/tv_p_Eo_hQdtVP

**Best of Sony TV Shows**
https://www.jiotv.com/list/best-of-sony---tv-shows/tv_p_IqW4l9_LdK

**Comment by virubhai22** [comment]
> > @virubhai22
> 
> Sony channels are also working on JioTV with new updates. **Sony For You** https://www.jiotv.com/list/sony-for-you/tv_p_Eo_hQdtVP
> 
> **Best of Sony TV Shows** https://www.jiotv.com/list/best-of-sony---tv-shows/tv_p_IqW4l9_LdK

Sony channel unable to play in my kodi add on
