### ISSUE TITLE
Someone please provide a working Discord link | Sony channels are not working

### ISSUE THREAD

**Issue by PadekarPratap** [tobalan/tobalan.github.io#38]

**Comment by technofreak24** [comment]
All Sony channels are working fine. Photos attached below:
![IMG_20240430_213150](https://github.com/tobalan/tobalan.github.io/assets/121749085/a5610347-7801-4d6a-8985-5752d8f6c49a)
![IMG_20240430_213125](https://github.com/tobalan/tobalan.github.io/assets/121749085/b8f117d1-72fc-4d7b-989c-75ae4ad9300e)
![IMG_20240430_213049](https://github.com/tobalan/tobalan.github.io/assets/121749085/aa4dd955-836c-431a-a21d-af95aaaea799)

**Comment by virubhai22** [comment]
![Screenshot 2024-05-02 023819](https://github.com/tobalan/tobalan.github.io/assets/115803193/becdeb90-9a6c-4b88-9b10-6b62a1843980)
![Screenshot 2024-05-02 023909](https://github.com/tobalan/tobalan.github.io/assets/115803193/661f6bc4-bd5f-4641-8d2e-528b9436428f)

Thanks to @technofreak24 for helping me restore Sony channel
![Screenshot 2024-05-02 030236](https://github.com/tobalan/tobalan.github.io/assets/115803193/70357247-4c1b-4f0d-91c0-1baf8c90947d)


![Screenshot 2024-05-02 030402](https://github.com/tobalan/tobalan.github.io/assets/115803193/c0402150-1eaa-4a18-931a-6b26aa1adeb9)

![Screenshot 2024-05-02 031110](https://github.com/tobalan/tobalan.github.io/assets/115803193/3fbff984-3203-493f-a201-895ad17b11c2)
![Screenshot 2024-05-02 031211](https://github.com/tobalan/tobalan.github.io/assets/115803193/89f59e3d-c240-4a59-a8e4-fdb391037cbe)

If u want to restore sony channels plz contact @technofreak24 he is very helpful corporate and nice guy.

**Comment by PadekarPratap** [comment]
@technofreak24 When I open any sony channel it shows the usual JIOTV window that channel will start later. Can you please help me to turn the sony channel on?

**Comment by PadekarPratap** [comment]
@technofreak24 @virubhai22 whenever I open a Sony Channel it shows the following window...
![WhatsApp Image 2024-05-07 at 7 28 05 PM](https://github.com/tobalan/tobalan.github.io/assets/99421898/f70af555-8178-405d-a636-aec9eb4bfba3)
Can you please give me a step by step guide on how can I resolve this issue. It's bugging me for quite a while now!

**Comment by rjprimeverse** [comment]
@technofreak24 can you please give me your telegram id I want to connect you on that ! @technofreak24

**Comment by kush0078787** [comment]
Please help us in watching sony channels.We are unable to watch these channels

**Comment by Jyoti-Kabir** [comment]
> All Sony channels are working fine. Photos attached below: ![IMG_20240430_213150](https://private-user-images.githubusercontent.com/121749085/326891257-a5610347-7801-4d6a-8985-5752d8f6c49a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjgzODksIm5iZiI6MTcxNjgyODA4OSwicGF0aCI6Ii8xMjE3NDkwODUvMzI2ODkxMjU3LWE1NjEwMzQ3LTc4MDEtNGQ2YS04OTg1LTU3NTJkOGY2YzQ5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNjQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDY1YmQzNzExZThiYmNkYWQ2NTk1NzJiZDA3Y2UxNzkwYTQzNTg4MTg3NmQ3ZGFkNjYwNDMxYmFmNWRjZmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lc1rB8BkrNbBdHp5UqUEv55Iwvn_ZU0F6qJmWUVNfEE) ![IMG_20240430_213125](https://private-user-images.githubusercontent.com/121749085/326891597-b8f117d1-72fc-4d7b-989c-75ae4ad9300e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjgzODksIm5iZiI6MTcxNjgyODA4OSwicGF0aCI6Ii8xMjE3NDkwODUvMzI2ODkxNTk3LWI4ZjExN2QxLTcyZmMtNGQ3Yi05ODljLTc1YWU0YWQ5MzAwZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNjQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTYxOGFhYjZhN2M4MjcyOWRlNThjN2FmOTExZmExY2JiNjY4YWNlN2MxZDk1MzZkYjZlZjE1ZmQyOTQ4MWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pFrCZJOEOow1z8qoEgKSwK-ycOO5d8hPVyhdT2LlB8s) ![IMG_20240430_213049](https://private-user-images.githubusercontent.com/121749085/326891952-aa4dd955-836c-431a-a21d-af95aaaea799.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjgzODksIm5iZiI6MTcxNjgyODA4OSwicGF0aCI6Ii8xMjE3NDkwODUvMzI2ODkxOTUyLWFhNGRkOTU1LTgzNmMtNDMxYS1hMjFkLWFmOTVhYWFlYTc5OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNjQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGJlMGJmYWYyNDZlZjg4OGEwYjFiMGJhYjc0YWVkN2YzNGVhZDVmNGU0OGViYTcwN2JkNDkyZTg4OGI1ODdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TI1memb9uL-55I0K5S3znd3gZkJxhHrr_9hz1PH3P5U)

My stream is also showing the "Stay Tuned" line on SET HD. Please tell me if there's a solution. And by the way, could you please tell what interface is that? How can I have that?

**Comment by niracle** [comment]
> ![Screenshot 2024-05-02 023819](https://private-user-images.githubusercontent.com/115803193/327250898-becdeb90-9a6c-4b88-9b10-6b62a1843980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTIzMTQsIm5iZiI6MTcxNjg5MjAxNCwicGF0aCI6Ii8xMTU4MDMxOTMvMzI3MjUwODk4LWJlY2RlYjkwLTlhNmMtNGI4OC05YjEwLTZiNjJhMTg0Mzk4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMDI2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzI5ZmMxMzYxYmE5NDA1MDIxY2RjZGYwMmU0NmQ0NWQ2ZTEzMTYwNzU2OGFiOWI4ZThmOTkyYjQyMjZmNzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zem2ddhU9XIlqkVRwZJkSR_F85WiqaTHT2s__lpdytI) ![Screenshot 2024-05-02 023909](https://private-user-images.githubusercontent.com/115803193/327250977-661f6bc4-bd5f-4641-8d2e-528b9436428f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTIzMTQsIm5iZiI6MTcxNjg5MjAxNCwicGF0aCI6Ii8xMTU4MDMxOTMvMzI3MjUwOTc3LTY2MWY2YmM0LWJkNWYtNDY0MS04ZDJlLTUyOGI5NDM2NDI4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMDI2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTRhZWRmNmYzMWJmMTg0Y2YwM2MzNzhiMTEzYTUyYzE3M2YyYzcyMDgzMzUxYjk5OTg2ODk2ZjRkNTE1YWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gJpmkZHZn8aPM9HXPzNhoXQ-DsM0xc1tsT_uo-viqq0)
> 
> Thanks to @technofreak24 for helping me restore Sony channel ![Screenshot 2024-05-02 030236](https://private-user-images.githubusercontent.com/115803193/327256403-70357247-4c1b-4f0d-91c0-1baf8c90947d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTIzMTQsIm5iZiI6MTcxNjg5MjAxNCwicGF0aCI6Ii8xMTU4MDMxOTMvMzI3MjU2NDAzLTcwMzU3MjQ3LTRjMWItNGYwZC05MWMwLTFiYWY4YzkwOTQ3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMDI2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmM5MzFhNDU5ZDJlZTg4M2IxY2ZkZTMxMzIyZTk4MWJiNzgxN2MyOWJmMGY0YTVjMjMxMDY0ZmMyZmI5MGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mjwA6vxefPQ16WocGVNFcyDBOQ24ndF2dReHir1iVuU)
> 
> ![Screenshot 2024-05-02 030402](https://private-user-images.githubusercontent.com/115803193/327256602-c0402150-1eaa-4a18-931a-6b26aa1adeb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTIzMTQsIm5iZiI6MTcxNjg5MjAxNCwicGF0aCI6Ii8xMTU4MDMxOTMvMzI3MjU2NjAyLWMwNDAyMTUwLTFlYWEtNGExOC05MzFhLTZiMjZhYTFhZGViOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMDI2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2RiMjRjOTlhYjc2MDFiZWViNTlkOWNkNzJhZTZiNmUzOWRkOWY3ZDViYmRlMTA3NDUwMDk5MTNkNmVlMWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s0-CMYQhEjtbZCVgoKpmFzaSPIo-2cM4fB_Jy0xdxkg)
> 
> ![Screenshot 2024-05-02 031110](https://private-user-images.githubusercontent.com/115803193/327256752-3fbff984-3203-493f-a201-895ad17b11c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTIzMTQsIm5iZiI6MTcxNjg5MjAxNCwicGF0aCI6Ii8xMTU4MDMxOTMvMzI3MjU2NzUyLTNmYmZmOTg0LTMyMDMtNDkzZi1hMjAxLTg5NWFkMTdiMTFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMDI2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2NjOTdlNDc1ZjBiNjZlNzUwYzYwM2U0NzRkMmY0NDQ3ODBhNzliMDJmODg0YjEwZThkN2I0NzkxZmU1OTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cQzG7fHVC9VgpnrncqocVqcLALO60Hlk5IsLLUailpY) ![Screenshot 2024-05-02 031211](https://private-user-images.githubusercontent.com/115803193/327256945-89f59e3d-c240-4a59-a8e4-fdb391037cbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTIzMTQsIm5iZiI6MTcxNjg5MjAxNCwicGF0aCI6Ii8xMTU4MDMxOTMvMzI3MjU2OTQ1LTg5ZjU5ZTNkLWMyNDAtNGE1OS1hOGU0LWZkYjM5MTAzN2NiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxMDI2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTU2OTQ0YmNhZmQzOTU2MTkwMDU0MzdlNjIxYjJjOGVmMDkwZTMzOGZhNzM4YTk5YjYyNDQ0Y2ZlMDRmM2VjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L15z_8Isnykyj9IfkcE2QCwfK8WFA2gkoB_39E-Wz04)
> 
> If u want to restore sony channels plz contact @technofreak24 he is very helpful cooperative and nice guy.

@virubhai22 can you guide on what steps you took under guidance from @technofreak24

**Comment by technofreak24** [comment]
> @Jyoti-Kabir what interface is that? How can I have that?

Interface is **Quartz skin addon** for **KODI Matrix v19.x or Nexus v20.x**

Turn ON the switch "Redirect Sony / Extra Channels" in the API/URL tab of Settings
* Extra channels option will make Sony channels work (except Ten Sports) & add Sony BBC Earth HD, Sony Pix HD, NDTV Marathi, Ishara TV, Nazara TV, Gubbare TV etc that are usually not available.

![IMG_20240605_210211~2](https://github.com/tobalan/tobalan.github.io/assets/121749085/83fcd606-ef23-4b03-8848-c1b7bbddec5c)

**Comment by virubhai22** [comment]
> > All Sony channels are working fine. Photos attached below: ![IMG_20240430_213150](https://private-user-images.githubusercontent.com/121749085/326891257-a5610347-7801-4d6a-8985-5752d8f6c49a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjgzODksIm5iZiI6MTcxNjgyODA4OSwicGF0aCI6Ii8xMjE3NDkwODUvMzI2ODkxMjU3LWE1NjEwMzQ3LTc4MDEtNGQ2YS04OTg1LTU3NTJkOGY2YzQ5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNjQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDY1YmQzNzExZThiYmNkYWQ2NTk1NzJiZDA3Y2UxNzkwYTQzNTg4MTg3NmQ3ZGFkNjYwNDMxYmFmNWRjZmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lc1rB8BkrNbBdHp5UqUEv55Iwvn_ZU0F6qJmWUVNfEE) ![IMG_20240430_213125](https://private-user-images.githubusercontent.com/121749085/326891597-b8f117d1-72fc-4d7b-989c-75ae4ad9300e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjgzODksIm5iZiI6MTcxNjgyODA4OSwicGF0aCI6Ii8xMjE3NDkwODUvMzI2ODkxNTk3LWI4ZjExN2QxLTcyZmMtNGQ3Yi05ODljLTc1YWU0YWQ5MzAwZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNjQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTYxOGFhYjZhN2M4MjcyOWRlNThjN2FmOTExZmExY2JiNjY4YWNlN2MxZDk1MzZkYjZlZjE1ZmQyOTQ4MWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pFrCZJOEOow1z8qoEgKSwK-ycOO5d8hPVyhdT2LlB8s) ![IMG_20240430_213049](https://private-user-images.githubusercontent.com/121749085/326891952-aa4dd955-836c-431a-a21d-af95aaaea799.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjgzODksIm5iZiI6MTcxNjgyODA4OSwicGF0aCI6Ii8xMjE3NDkwODUvMzI2ODkxOTUyLWFhNGRkOTU1LTgzNmMtNDMxYS1hMjFkLWFmOTVhYWFlYTc5OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxNjQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGJlMGJmYWYyNDZlZjg4OGEwYjFiMGJhYjc0YWVkN2YzNGVhZDVmNGU0OGViYTcwN2JkNDkyZTg4OGI1ODdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TI1memb9uL-55I0K5S3znd3gZkJxhHrr_9hz1PH3P5U)
> 
> My stream is also showing the "Stay Tuned" line on SET HD. Please tell me if there's a solution. And by the way, could you please tell what interface is that? How can I have that?

https://github.com/tobalan/tobalan.github.io/issues/42#issuecomment-2150385862

**Comment by GTTech2305** [comment]
Is this working now again as i have this API zip but channel is not working

**Comment by nagorimayank** [comment]
Hi @technofreak24 
Could you help me as well to get a working JioTV in Kodi please? I tried adding the Channel URL and turned on Redirect Sony channel toggle. But it didn't work as yet. 

Appreciate your assistance here. Thanks in advance.
