### ISSUE TITLE
Connection Error on Airtel Network 

### ISSUE THREAD

**Issue by PadekarPratap** [tobalan/tobalan.github.io#43]
I was using Kodi and Tobalan on my local ISP for a few months and it was working fine. A few days ago I switched to Airtel Xtream Fiber connection and kodi started showing connection error. I'm sure that the TV is connected to Wi-Fi and the internet is also working as I can play YouTube and stream other content. However on Kodi whenever I try to start any channel it throws the following error:

Error while Playback, check connection
(connection aborted(104, 'connection reset by peer'))

Here are the Screenshots: 

![WhatsApp Image 2024-05-28 at 5 39 07 PM](https://github.com/tobalan/tobalan.github.io/assets/99421898/1e9dd003-d029-4248-b347-219df5134a9c)

![WhatsApp Image 2024-05-28 at 5 39 08 PM](https://github.com/tobalan/tobalan.github.io/assets/99421898/b956e6f9-9a80-4f2c-ab58-30597fb6339e)

![WhatsApp Image 2024-05-28 at 5 39 08 PM (1)](https://github.com/tobalan/tobalan.github.io/assets/99421898/b4449691-ee7b-492e-8e35-193be3f3c491)

I'm pretty sure this is due to the Airtel Wi-Fi that I'm using. Can someone please help me on this issue?

**Comment by lavish440** [comment]
Try using any other network. This issue is very common on Airtel network.
