### ISSUE TITLE
Sony Channel is Not working in current versions getting connection error

### ISSUE THREAD

**Issue by GTTech2305** [tobalan/tobalan.github.io#44]
Hello Team.

Please fix this issue for Sony Channels, as its not working from past 2  to 3 month in this repo, and another modified repo also stop working now.

**Comment by RaahgirTech** [comment]
> Hello Team.
> 
> Please fix this issue for Sony Channels, as its not working from past 2 to 3 month in this repo, and another modified repo also stop working now.

Please try with the below link on any of the IPTV players.

http://103.72.179.30:1935/GECHindi/SONY.stream_720p/Playlist.m3u8
