### ISSUE TITLE
Error while playback check connection  < not supported between instances of int and str

### ISSUE THREAD

**Issue by vkkindia** [tobalan/tobalan.github.io#47]
Iam using this in lg webos  kodi, getting this error message
Error while playback check connection 
< not supported between instances of int and str

**Comment by technofreak24** [comment]
> @vkkindia  `< not supported between instances of int and str`

It means there is a comparison operator **"less than (<)"** between integer and string types in the play() function in main.py file of the addon. It must be on the line where the playlist streams count in playback m3u is compared to a number like 6 or 7 or 8 written in the file which is now not needed.
The solution is to remove the comparison line with the lines relying on the comparison OR convert the string to an integer value by **int('theStringComesHere')**

**Comment by vkkindia** [comment]
line no 156
			if E.is_variant and(E.version is _N or E.version<7):
