### ISSUE TITLE
Jio tv is not working on kodi!!

### ISSUE THREAD

**Issue by Xchemister** [tobalan/tobalan.github.io#48]
Hey guys. Everything works fine until you click on any channel it triggers blue loading circles of kodi and then nothing happens. The issues started 4th July around 2PM GMT +5.30. Can anyone look into it? Thanks!

**Comment by Iliyaz-Syed** [comment]
Yeah Same for me too. Just loads with the blue circle twice and nothing seems to happen. Even tried re-doing everything. Same problem continues. Let us know if anyone knows how to solve this. Thanks

**Comment by nithinbhandary** [comment]
same here

**Comment by Gokulakannanaj** [comment]
@krreet @lavish440 @tobalan  Could you please look into this issue on priority?

**Comment by lavish440** [comment]
Work in progress

**Comment by sendy50** [comment]
Same here i was reinstalled all things but not work

**Comment by AishikDasgupta** [comment]
i tried reinstalling the whole proccess and nothing is working, that's so bad, please if anyone finds a solution let me know

**Comment by subhajit2610** [comment]
Same here

**Comment by lavish440** [comment]
Read the comment above

**Comment by AishikDasgupta** [comment]
> Read the comment above

How long might it take?

**Comment by lavish440** [comment]
> ?

Can't tell

**Comment by lavish440** [comment]
> > Read the comment above
> 
> How long might it take?

Can't say

**Comment by shri1990** [comment]
Workaround solution on this page : https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331

**Comment by Gokulakannanaj** [comment]
> Workaround solution on this page : [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331)

Could you please explain how to achieve this? Do I want to download that zip file for installation?

**Comment by shri1990** [comment]
> > Workaround solution on this page : [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331)
> 
> Could you please explain how to achieve this? Do I want to download that zip file for installation?

Make sure you are on Kodi v20.5 and install the jiotv addon zip file https://github.com/krreet/plugin.video.jiotv/archive/refs/tags/v2.0.25.zip

**Comment by Gokulakannanaj** [comment]
> > > Workaround solution on this page : [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331)
> > 
> > 
> > Could you please explain how to achieve this? Do I want to download that zip file for installation?
> 
> Make sure you are on Kodi v20.5 and install the jiotv addon zip file https://github.com/krreet/plugin.video.jiotv/archive/refs/tags/v2.0.25.zip

Thanks for your support, I installed the Kodi and also having the Zip on my local. Zip file not displayed when I'm trying to install it by using Zip file. Am I missing anything here?

**Comment by Gokulakannanaj** [comment]
> > > Workaround solution on this page : [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331)
> > 
> > 
> > Could you please explain how to achieve this? Do I want to download that zip file for installation?
> 
> Make sure you are on Kodi v20.5 and install the jiotv addon zip file https://github.com/krreet/plugin.video.jiotv/archive/refs/tags/v2.0.25.zip

Thanks man, It's working as expected

**Comment by Iliyaz-Syed** [comment]
> Workaround solution on this page : [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331)

Thanks Man , It's working.

**Comment by shri1990** [comment]
> Work in progress

Hi bro, even though we got a workaround solution but it would be great if you could provide an updated zip file with catchup working which works on latest kodi version.
Take your time..

**Comment by lavish440** [comment]
> > Work in progress
> 
> Hi bro, even though we got a workaround solution but it would be great if you could provide an updated zip file with catchup working which works on latest kodi version.
> Take your time..
> Appreciate your support.

The EPG works on the addon. The issue is the EPG generation. If you have an always running computer or a homelab server, you can generate the EPG yourself. It only takes around 1 minute for me.

**Comment by shri1990** [comment]
> > > Work in progress
> > 
> > 
> > Hi bro, even though we got a workaround solution but it would be great if you could provide an updated zip file with catchup working which works on latest kodi version.
> > Take your time..
> > Appreciate your support.
> 
> The EPG works on the addon. The issue is the EPG generation. If you have an always running computer or a homelab server, you can generate the EPG yourself. It only takes around 1 minute for me.

Unfortunately i dont have any lab server.. Can you provide a EPG remote URL that i can set in the IPTV simple client..
