### ISSUE TITLE
channels are not playing in kodi

### ISSUE THREAD

**Issue by nithinbhandary** [tobalan/tobalan.github.io#49]

**Comment by AishikDasgupta** [comment]
same here Kodi tobalan repository ain't working

**Comment by Rengpuia** [comment]
Same here, please update

**Comment by Karthikkt851** [comment]
Guys ,please fix this ,jio tv is not working from 4th July 2024

**Comment by ayusht9** [comment]
`One or more items failed to play. Check the log for more infomation about this message`

- Reinstalling doesn't fix the problem.
- Tried other repos too, none of them are working

**Comment by subhajit2610** [comment]
Same here, jio  TV not working

**Comment by manjeet479** [comment]
Any update on this? I think API needs to be updated

**Comment by technofreak24** [comment]
Solution is on this page https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331

**Comment by nithinbhandary** [comment]
> Solution is on this page https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331

this one is working fine
thank you

**Comment by Karthikkt851** [comment]
Thanks teams for quick fix .it's working now

**Comment by arunchakravarthy86** [comment]
Thanks this is working. 
Wondering how long it will work and what next? When can we upgrade to kodi v 21?

**Comment by abhashj** [comment]
@arunchakravarthy86 how did you add this repository as source? I am getting no zip files for 2.0.25 within Kodi

**Comment by arunchakravarthy86** [comment]
You don't need to add as source.. just install from zip file and browse the
usb or harddisk where you have the zip file to select and proceed.
