### ISSUE TITLE
Jio tv addon all channel playback issue from 4th July

### ISSUE THREAD

**Issue by debapatra23** [tobalan/tobalan.github.io#50]
Please update the files

**Comment by Harikrishnan009** [comment]
Yeah the files are not updated I guess. Tried reinstalling and setting up again, but the code doesn't work

**Comment by debapatra23** [comment]
> Any update on this?

No update, i still searching for alternative 🤧
My dad don't know anything related iptv he was using kodi jio tv from last 3y & it's so user friendly

If I get any update i atteched the update here

**Comment by Xchemister** [comment]
https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331
It's a working method check out.
