### ISSUE TITLE
Tobalan stopped working / alternative

### ISSUE THREAD

**Issue by Harikrishnan009** [tobalan/tobalan.github.io#52]
Is there any other alternativs for the same?

**Comment by ajay7413** [comment]
Yes I also face issue

**Comment by ajay7413** [comment]
When I click on any chennal it load to some seconds then the chennal not start and I have try the all process of installation of Jio tv on Kodi 3 time but it also not working

**Comment by Harikrishnan009** [comment]
> When I click on any chennal it load to some seconds then the chennal not start and I have try the all process of installation of Jio tv on Kodi 3 time but it also not working 

Resetting the app doesn't work, have tried the troubleshooting

**Comment by technofreak24** [comment]
@Harikrishnan009 Solution is given on https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331

**Comment by Karthikkt851** [comment]
Team, 

It would be better if we can change the channel just like other dish tv using this tobolan jio tv ..Please develop this code . Senior citizens face difficulty in changing the channel

**Comment by Harikrishnan009** [comment]
> @Harikrishnan009 Solution is given on https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331

Can you please provide me the steps?

**Comment by Virusvilla** [comment]
Just use old version of jio plugin 2.0.25 with kodi version 20. Its working fine.
