### ISSUE TITLE
Jio tv not working 

### ISSUE THREAD

**Issue by Parth27122002** [tobalan/tobalan.github.io#55]
Jiotv not working on kodi tobalan please give a perfect solution

**Comment by jobs-code** [comment]
https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331 
Try this

**Comment by sanchetkore** [comment]
> [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331) Try this

This too is not working

**Comment by Parth27122002** [comment]
I expl

> [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331) Try this

Let me explain I understand this setup first uninstall kodi and install kodi nexus 20.5 

Then install this plugin zip file in kodi 20.5 nexus 

Then login via OTP 

And done 👍🏻 

Problem solved 
Try this Step by step

**Comment by pushpendra010** [comment]
> 
> 
> > [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331) Try this
> 
> Let me explain I understand this setup first uninstall kodi and install kodi nexus 20.5 
> 
> Then install this plugin zip file in kodi 20.5 nexus 
> 
> Then login via OTP 
> 
> And done 👍🏻 
> 
> Problem solved 
> Try this Step by step
> 

But Kodi doesn't show the zip file in install from the zip file option

**Comment by RaahgirTech** [comment]
> > > [krreet/plugin.video.jiotv#132 (comment)](https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331) Try this
> > 
> > 
> > Let me explain I understand this setup first uninstall kodi and install kodi nexus 20.5
> > Then install this plugin zip file in kodi 20.5 nexus
> > Then login via OTP
> > And done 👍🏻
> > Problem solved
> > Try this Step by step
> 
> But Kodi doesn't show the zip file in install from the zip file option

It doesn't show sometimes, download the file on any of your computer and then either transfer it on TV/Firetvstick then try to install it.

Note: The name should be as it is 'plugin.video.jiotv-2.0.25.zip' as per the setup file else kodi will not detect it.
Cheers!!!
Enjoy!

**Comment by vijayraje11** [comment]
Jiotv not working with tobalan link from last 5 days ..please give me soution or update tobalan files

**Comment by RaahgirTech** [comment]
> Jiotv not working with tobalan link from last 5 days ..please give me soution or update tobalan files

Solution - https://github.com/krreet/plugin.video.jiotv/issues/132#issuecomment-2211020331
