### ISSUE TITLE
Jio working method 

### ISSUE THREAD

**Issue by debapatra23** [tobalan/tobalan.github.io#56]
Use this JioTV version
https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25

& Install kodi 20.5 version
https://mirrors.kodi.tv/releases/android/arm/kodi-20.5-Nexus-armeabi-v7a.apk

Remember all channel work except Sony & login with OTP, password method didn't work

**Comment by gitcodnik** [comment]
Thanks @debapatra23  this is method is working.

**Comment by tishwanth** [comment]
what link should i add in add source ?  can someone share the link for v2.0.25 since "tobalan.github.io" only downloads 2.3.9 version.

**Comment by sendy50** [comment]
Thanks @debapatra23 please can you give me some steps how can i install etc

**Comment by dheeraj120** [comment]
Hi all 

> Use this JioTV version https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25
> 
> & Install kodi 20.5 version https://mirrors.kodi.tv/releases/android/arm/kodi-20.5-Nexus-armeabi-v7a.apk
> 
> Remember all channel work except Sony & login with OTP, password method didn't work

Thank you it does work, I want to add couple of things 
1. No need of old Tobalen git repo to be installed skip this step and directly go ahead and install the above plugin to avoid error code 'playback failed. One or more items failed to play.'
2. While installing the plugin if you don't find the zip file in your downloaded directory make sure you give full file ready access for kodi from the settings . I faced this issue 😅.
3. And make sure you turn off the auto update feature for both Kodi app as well as for the plugins .

**Comment by saurabhchhaya** [comment]
Thanks Admin

**Comment by basheersafu** [comment]
What about kodi running in libreelec in raspberry pi ,do I have to downgrade kodi omega to nexus, now I am using kodi 21 jio tv not working since 3 weaks

**Comment by Beryl590** [comment]
Not working again since 22-Jul. Error 😟
Any thoughts @technofreak24

**Comment by Sumit9198424421** [comment]
Is it working now?
