### ISSUE TITLE
Jio tv not working on kodi

### ISSUE THREAD

**Issue by manishp608** [tobalan/tobalan.github.io#63]
It was working till this afternoon. now it can only play catchup programs and not live tv. why? please solve it. it was not working when i did from tobalan but i followed this https://forum.kodi.tv/showthread.php?tid=378091 and then downloaded some kiran zip file and it worked. now it is showing error when i play

**Comment by manishp608** [comment]
added

**Comment by mangeshyevale** [comment]
> It was working till this afternoon. now it can only play catchup programs and not live tv. why? please solve it. it was not working when i did from tobalan but i followed this https://forum.kodi.tv/showthread.php?tid=378091 and then downloaded some kiran zip file and it worked. now it is showing error when i play

I am also facing the same issue since afternoon.
Please share any fix/update

**Comment by manishp608** [comment]
I think they should do something

**Comment by manishp608** [comment]
We have to wait. For now we have to watch only catchup tv

**Comment by Sumit9198424421** [comment]
Plz find  some solution
