### ISSUE TITLE
Plugin not working anymore 

### ISSUE THREAD

**Issue by Parth2712002** [tobalan/tobalan.github.io#64]
Plugin jio tv for kodi add on is not more work it's showing http error please give a solution as soon as possible 🙏🏻

**Comment by Sumit9198424421** [comment]
Same problem again.  Stopped working as on 21.7.24

**Comment by akshayabusa007** [comment]
its stopped working same problem here as well

**Comment by Sumit9198424421** [comment]
Let me know if you find any solution..i am also searching for resolution
