### ISSUE TITLE
Jio tv is not working today, Till yesterday it was working fine. Kodi v20.5. Plugin v2.0.25

### ISSUE THREAD

**Issue by DeekshithVelmula** [tobalan/tobalan.github.io#66]
HTTP ERROR:
401 CLIENT error. Unauthorised URL.......

**Comment by Sumit9198424421** [comment]
Same problem here.plz find solution 🙏

**Comment by DeekshithVelmula** [comment]
Working with below zip file
[plugin.video.jiotv+.zip](https://github.com/user-attachments/files/16352455/plugin.video.jiotv%2B.zip)

**Comment by Sumit9198424421** [comment]
Which version of kodi

**Comment by Sumit9198424421** [comment]
Kodi version?

**Comment by DeekshithVelmula** [comment]
Kodi version: 20.5

**Comment by dns96** [comment]
Thanks sir it's working with above plugin. Kodi version 20.5
