### ISSUE TITLE
Jio Working Method🥸 i cracked it boys

### ISSUE THREAD

**Issue by debapatra23** [tobalan/tobalan.github.io#68]
Use this Add-on
https://t.me/DenverIsAlivee/1979

Kodi version 20.5
https://mirrors.kodi.tv/releases/android/arm/kodi-20.5-Nexus-armeabi-v7a.apk

Login with Jio number & OTP 😁👍
Credit https://t.me/DenverIsAlivee

**Comment by debapatra23** [comment]
Video tutorials link
https://t.me/denver_iptv/221134

**Comment by Karthikkt851** [comment]
Thanks @debapatra23  it's working ,is there a chance to code to change the channel just like dish tv

**Comment by TecnikOfficial** [comment]
i cannot download using telegram is there other link or repo ?

**Comment by nagorimayank** [comment]
Thank you @debapatra23 !!!

**Comment by TecnikOfficial** [comment]
does anyone github link instead of telegram ?

**Comment by technofreak24** [comment]
**Working great** 🙂👇🏻
JioCinema channels added in **v2.0.41** & all channels are working !

![screenshot00026_100803](https://github.com/user-attachments/assets/3f5b79c7-78d4-4fb9-801c-bbb56e807677)

![screenshot00029_100825](https://github.com/user-attachments/assets/aefeb740-5202-4967-a9e5-327d29c7addd)

**Comment by DeekshithVelmula** [comment]
[plugin.video.jiotv+.zip](https://github.com/user-attachments/files/16352447/plugin.video.jiotv%2B.zip)
Find the zip file here.

**Comment by DeekshithVelmula** [comment]
@debapatra23 Please fix sony channels. Sony channels are not working.

**Comment by Parth2712002** [comment]
> Use this Add-on https://t.me/DenverIsAlivee/1979
> 
> Kodi version 20.5 https://mirrors.kodi.tv/releases/android/arm/kodi-20.5-Nexus-armeabi-v7a.apk
> 
> Login with Jio number & OTP 😁👍 Credit https://t.me/DenverIsAlivee

Bhai hats off 🙏🏻

**Comment by Parth2712002** [comment]
> > Use this Add-on https://t.me/DenverIsAlivee/1979
> > Kodi version 20.5 https://mirrors.kodi.tv/releases/android/arm/kodi-20.5-Nexus-armeabi-v7a.apk
> > Login with Jio number & OTP 😁👍 Credit https://t.me/DenverIsAlivee
> 
> Bhai hats off 🙏🏻

Bhai ip tv kese set kare list bhar tv option me lane k liye

**Comment by TecnikOfficial** [comment]
> [plugin.video.jiotv+.zip](https://github.com/user-attachments/files/16352447/plugin.video.jiotv%2B.zip) @TecnikOfficial Download the above zip file.

tysm 👍

**Comment by Beryl590** [comment]
Thanx a lot @debapatra23  🙏

**Comment by SkieyeN** [comment]
Working for 2 day's, again Even this stopped working from 10 mins before giving http error and playback failed

**Comment by SkieyeN** [comment]
@debapatra23 its stopped working now..
