### ISSUE TITLE
Jio tv not working again with new plugin

### ISSUE THREAD

**Issue by Karthikkt851** [tobalan/tobalan.github.io#72]
Hi team 

Again jio tv is not working in kodi .please help to fix it

**Comment by Karthikkt851** [comment]
Hi @debapatra23 
Can you please on this

**Comment by SkieyeN** [comment]
Same, not working.. Could anyone provide with the update.

**Comment by Xchemister** [comment]
Yeap. It's gone again! 😥

**Comment by debapatra23** [comment]
> Hi @debapatra23 Can you please help on this

I Trying to fix it

**Comment by Karthikkt851** [comment]
Hi @debapatra23 , thanks also is possible explain us why exactly this issue happens .we can also help when again this happen.I am not hardcore coder though 😜😂
